services:
  redis:
    image: ghcr.io/${GITHUB_REPOSITORY}/redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - redis-data:/data
    networks:
      - oda-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api-service:
    image: ghcr.io/${GITHUB_REPOSITORY}/api-service:latest
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    environment:
      - REDIS_URL=${REDIS_URL}
      - FASTAPI_PORT=${FASTAPI_PORT}
      - ODA_API_BASE_URL=${ODA_API_BASE_URL}
      - PYTHONUNBUFFERED=1
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - oda-network
    restart: unless-stopped

  nextjs:
    image: ghcr.io/${GITHUB_REPOSITORY}/nextjs:latest
    ports:
      - "${NEXTJS_PORT}:${NEXTJS_PORT}"
    environment:
      - FASTAPI_INTERNAL_URL=${FASTAPI_INTERNAL_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - PORT=${NEXTJS_PORT}
    depends_on:
      - api-service
    networks:
      - oda-network

volumes:
  redis-data:

networks:
  oda-network:
    driver: bridge